### PR TITLE
Links callsign's QRZ page in the table

### PR DESCRIPTION
**Pull request by simsnet**
Also repairs missing/broken HTML tags, page indent, and defaults opening the QRZ page in a new tab.

### CODE REVIEW

**Review by brianjester — APPROVED** [review]
looks good, I committed this one to master

**Review by brianjester — COMMENTED** [review]
Also looks good, this is what I would have probably written not realizing it would reload in the same tab.  I commited the other one that opens in the other tab.

**Review by brianjester — COMMENTED** [review]
Didn't commit this one because it conflicted with the change I pushed to master a couple mins ago, but I should prolly fix a missing closure eh?

**Comment by simsnet** [comment]
The page didn't have any issues in the browser but Brackets showed red `</body>` and `</html>` tags.  I managed to find where the editor was comfortable with the completed tags.

`<main>...</main>` - https://prnt.sc/25wu8mq
`<div>...</div>` - https://prnt.sc/25wumft (closing tag on line 169)

Purely a cosmetic fix.

**Pull request closed without merging**
